server:
  port: 8085

spring:
  application:
    name: stock-service
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8762}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/stockdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
  flyway:
    enabled: true
  # Redis — stok cache
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 dakika (ms)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/ecommerce}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/ecommerce}/protocol/openid-connect/certs

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Stock Service API
    version: 1.0.0
    app:
      exception:
        verbose: ${EXCEPTION_VERBOSE:false}
